# Generated by Django 2.1.2 on 2019-05-25 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estudio_instituciones'),
        ('mpi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpi',
            name='paciente_mpi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Pacientes'),
        ),
    ]
