# Generated by Django 2.1.2 on 2019-07-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='talla',
            field=models.IntegerField(verbose_name='Talla'),
        ),
    ]
