# Generated by Django 2.1.2 on 2019-07-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190711_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='imc',
            field=models.FloatField(verbose_name='Imc'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='talla',
            field=models.FloatField(verbose_name='Talla'),
        ),
    ]
