# Generated by Django 2.1.2 on 2019-05-22 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estudio_pacientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='instituciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.InstitucionMedica'),
        ),
    ]
