# Generated by Django 2.1.2 on 2019-06-28 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ergometria',
            fields=[
                ('id_ergo', models.AutoField(primary_key=True, serialize=False)),
                ('ciclo_ergo', models.BooleanField(default=False)),
                ('banda_ergo', models.BooleanField(default=False)),
                ('carga', models.IntegerField(null=True, verbose_name='Carga')),
                ('fc_basal', models.IntegerField(null=True, verbose_name='Fc basal')),
                ('tas_basal', models.IntegerField(null=True, verbose_name='Tas basal')),
                ('tad_basal', models.IntegerField(null=True, verbose_name='Tad basal')),
                ('fc_esfuerzo', models.IntegerField(null=True, verbose_name='Fc esfuerzo')),
                ('tas_esfuerzo', models.IntegerField(null=True, verbose_name='Tas esfuerzo')),
                ('tad_esfuerzo', models.IntegerField(null=True, verbose_name='Tad esfuerzo')),
                ('mets', models.IntegerField(null=True, verbose_name='Mets')),
                ('st', models.CharField(max_length=50)),
                ('st_mm', models.IntegerField(null=True, verbose_name='St mm')),
                ('ta_plana', models.BooleanField(default=False)),
                ('motivo_suspencion', models.CharField(max_length=50)),
                ('arritmia_sv', models.CharField(max_length=50)),
                ('arritmia_v', models.CharField(max_length=50)),
                ('sintomas', models.CharField(max_length=50)),
                ('fcm_edad', models.IntegerField(null=True, verbose_name='Fcm edad')),
                ('percent_fcmp', models.IntegerField(null=True, verbose_name='Percent fcmp')),
                ('itt', models.IntegerField(null=True, verbose_name='Itt')),
                ('paciente_ergo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Pacientes')),
            ],
        ),
    ]
