<<<<<<< HEAD
# Generated by Django 2.2.1 on 2019-06-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id_antecedentes', models.AutoField(primary_key=True, serialize=False)),
                ('fcrv_hta', models.BooleanField(default=False, null=True)),
                ('fcrv_dta', models.BooleanField(default=False, null=True)),
                ('fecha_fcrv_hta', models.DateField(null=True)),
                ('fecha_fcrv_dta', models.DateField(null=True)),
                ('anteced_fliar', models.BooleanField(default=False, null=True)),
                ('dislipemia', models.BooleanField(default=False, null=True)),
                ('estres', models.BooleanField(default=False, null=True)),
                ('tabaquismo', models.BooleanField(default=False, null=True)),
                ('ex_tabaquismo', models.BooleanField(default=False, null=True)),
                ('sedentarismo', models.BooleanField(default=False, null=True)),
                ('chagas', models.BooleanField(default=False, null=True)),
                ('marcapasos', models.BooleanField(default=False, null=True)),
                ('resincron', models.BooleanField(default=False, null=True)),
                ('cdi', models.BooleanField(default=False, null=True)),
                ('crm_hta', models.BooleanField(default=False, null=True)),
                ('fecha_crm_hta', models.DateTimeField(null=True)),
                ('pm', models.BooleanField(default=False, null=True)),
                ('pm_da', models.BooleanField(default=False, null=True)),
                ('pm_dg', models.BooleanField(default=False, null=True)),
                ('pm_cx', models.BooleanField(default=False, null=True)),
                ('pr', models.BooleanField(default=False, null=True)),
                ('pr_dg', models.BooleanField(default=False, null=True)),
                ('pr_cx', models.BooleanField(default=False, null=True)),
                ('pv', models.BooleanField(default=False, null=True)),
                ('pv_da', models.BooleanField(default=False, null=True)),
                ('pv_dg', models.BooleanField(default=False, null=True)),
                ('pv_cx', models.BooleanField(default=False, null=True)),
                ('infarto', models.BooleanField(default=False, null=True)),
                ('fecha_infarto_reciente', models.DateField(null=True)),
                ('atc1', models.BooleanField(default=False, null=True)),
                ('atc1_da', models.BooleanField(default=False, null=True)),
                ('atc1_dg', models.BooleanField(default=False, null=True)),
                ('atc1_cx', models.BooleanField(default=False, null=True)),
                ('atc1_cd', models.BooleanField(default=False, null=True)),
                ('atc1_stent_bms', models.BooleanField(default=False, null=True)),
                ('atc1_stent_des', models.BooleanField(default=False, null=True)),
                ('atc2', models.BooleanField(default=False, null=True)),
                ('atc2_da', models.BooleanField(default=False, null=True)),
                ('atc2_dg', models.BooleanField(default=False, null=True)),
                ('atc2_cx', models.BooleanField(default=False, null=True)),
                ('atc2_cd', models.BooleanField(default=False, null=True)),
                ('atc2_stent_bms', models.BooleanField(default=False, null=True)),
                ('atc2_stent_des', models.BooleanField(default=False, null=True)),
                ('atc3', models.BooleanField(default=False, null=True)),
                ('atc3_da', models.BooleanField(default=False, null=True)),
                ('atc3_dg', models.BooleanField(default=False, null=True)),
                ('atc3_cx', models.BooleanField(default=False, null=True)),
                ('atc3_cd', models.BooleanField(default=False, null=True)),
                ('atc3_stent_bms', models.BooleanField(default=False, null=True)),
                ('atc3_stent_des', models.BooleanField(default=False, null=True)),
                ('otros_antecedentes', models.TextField(null=True)),
                ('paciente_antecedente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Pacientes')),
            ],
        ),
    ]
=======
# Generated by Django 2.1.2 on 2019-05-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id_antecedentes', models.AutoField(primary_key=True, serialize=False)),
                ('fcrv_hta', models.BooleanField(default=False, null=True)),
                ('fcrv_dta', models.BooleanField(default=False, null=True)),
                ('anteced_fliar', models.BooleanField(default=False, null=True)),
                ('dislipemia', models.BooleanField(default=False, null=True)),
                ('estres', models.BooleanField(default=False, null=True)),
                ('tabaquismo', models.BooleanField(default=False, null=True)),
                ('ex_tabaquismo', models.BooleanField(default=False, null=True)),
                ('sedentarismo', models.BooleanField(default=False, null=True)),
                ('chagas', models.BooleanField(default=False, null=True)),
                ('marcapasos', models.BooleanField(default=False, null=True)),
                ('resincron', models.BooleanField(default=False, null=True)),
                ('cdi', models.BooleanField(default=False, null=True)),
                ('crm_hta', models.BooleanField(default=False, null=True)),
                ('pm', models.BooleanField(default=False, null=True)),
                ('pm_da', models.BooleanField(default=False, null=True)),
                ('pm_dg', models.BooleanField(default=False, null=True)),
                ('pm_cx', models.BooleanField(default=False, null=True)),
                ('pr', models.BooleanField(default=False, null=True)),
                ('pr_dg', models.BooleanField(default=False, null=True)),
                ('pr_cx', models.BooleanField(default=False, null=True)),
                ('pv', models.BooleanField(default=False, null=True)),
                ('pv_da', models.BooleanField(default=False, null=True)),
                ('pv_dg', models.BooleanField(default=False, null=True)),
                ('pv_cx', models.BooleanField(default=False, null=True)),
                ('infarto', models.BooleanField(default=False, null=True)),
                ('atc1', models.BooleanField(default=False, null=True)),
                ('atc1_da', models.BooleanField(default=False, null=True)),
                ('atc1_dg', models.BooleanField(default=False, null=True)),
                ('atc1_cx', models.BooleanField(default=False, null=True)),
                ('atc1_cd', models.BooleanField(default=False, null=True)),
                ('atc1_stent_bms', models.BooleanField(default=False, null=True)),
                ('atc1_stent_des', models.BooleanField(default=False, null=True)),
                ('atc2', models.BooleanField(default=False, null=True)),
                ('atc2_da', models.BooleanField(default=False, null=True)),
                ('atc2_dg', models.BooleanField(default=False, null=True)),
                ('atc2_cx', models.BooleanField(default=False, null=True)),
                ('atc2_stent_bms', models.BooleanField(default=False, null=True)),
                ('atc2_stent_des', models.BooleanField(default=False, null=True)),
                ('atc3', models.BooleanField(default=False, null=True)),
                ('atc3_da', models.BooleanField(default=False, null=True)),
                ('atc3_dg', models.BooleanField(default=False, null=True)),
                ('atc3_cx', models.BooleanField(default=False, null=True)),
                ('atc2_cd', models.BooleanField(default=False, null=True)),
                ('atc3_stent_bms', models.BooleanField(default=False, null=True)),
                ('atc3_stent_des', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
>>>>>>> 7927276fd1b2c4dd6dc819fd275d3e6d654cb1e2
