# Generated by Django 2.1.2 on 2019-05-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentes',
            name='fecha_crm_hta',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='fecha_fcrv_dta',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='fecha_fcrv_hta',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='fecha_infarto_reciente',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='otros_antecedentes',
            field=models.TextField(null=True),
        ),
    ]
