# Generated by Django 2.1.2 on 2019-05-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antec', '0002_auto_20190525_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentes',
            name='fecha_fcrv_dta',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='fecha_infarto_reciente',
            field=models.DateField(null=True),
        ),
    ]
