# Generated by Django 2.1.2 on 2019-05-28 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estudio_instituciones'),
        ('antec', '0003_auto_20190525_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentes',
            name='paciente_antecedente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Pacientes'),
        ),
    ]
